name: Auto-close wontfix issues

on:
  issues:
    types: [opened, labeled]

jobs:
  close-wontfix:
    runs-on: ubuntu-latest
    if: contains(github.event.issue.labels.*.name, 'wontfix')
    permissions:
      issues: write
    steps:
      - name: Close issue
        uses: peter-evans/close-issue@v3
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: This issue has been automatically closed because it is labeled as 'wontfix'.